import React, { useState } from 'react';
import {
  CalendarDays,
  CalendarCheck,
  Plus,
  Clock,
  MapPin,
  CheckCircle2,
  Calendar,
  AlertCircle,
  X,
  ExternalLink,
  ChevronLeft,
  ChevronRight,
  Shield,
  Trash2,
  Edit3,
} from 'lucide-react';
import { Appointment, BusinessProfile } from '../types';

interface AppointmentsViewProps {
  appointments: Appointment[];
  onAddAppointment: (appointment: Appointment) => void;
  onUpdateAppointmentStatus: (
    appointmentId: string,
    status: 'confirmed' | 'rescheduled' | 'cancelled' | 'completed'
  ) => void;
  businessProfile: BusinessProfile;
  onSyncGoogleCalendar: (apt: Appointment) => void;
  isGoogleConnected: boolean;
}

export const AppointmentsView: React.FC<AppointmentsViewProps> = ({
  appointments,
  onAddAppointment,
  onUpdateAppointmentStatus,
  businessProfile,
  onSyncGoogleCalendar,
  isGoogleConnected,
}) => {
  const [viewMode, setViewMode] = useState<'month' | 'week' | 'list'>('list');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingApt, setEditingApt] = useState<Appointment | null>(null);

  // Form state
  const [formCustomerName, setFormCustomerName] = useState('');
  const [formPhone, setFormPhone] = useState('');
  const [formEmail, setFormEmail] = useState('');
  const [formService, setFormService] = useState(businessProfile.services[0]?.name || 'Standard Service');
  const [formDate, setFormDate] = useState('2026-09-15');
  const [formTime, setFormTime] = useState('14:00');
  const [formAddress, setFormAddress] = useState(businessProfile.address);
  const [formPrice, setFormPrice] = useState(250);
  const [formNotes, setFormNotes] = useState('');

  const handleOpenNewModal = () => {
    setEditingApt(null);
    setFormCustomerName('');
    setFormPhone('');
    setFormEmail('');
    setFormService(businessProfile.services[0]?.name || 'Standard Diagnostic');
    setFormDate(new Date().toISOString().split('T')[0]);
    setFormTime('14:00');
    setFormAddress('Austin, TX');
    setFormPrice(249);
    setFormNotes('');
    setIsModalOpen(true);
  };

  const handleOpenReschedule = (apt: Appointment) => {
    setEditingApt(apt);
    setFormCustomerName(apt.customerName);
    setFormPhone(apt.customerPhone);
    setFormEmail(apt.customerEmail);
    setFormService(apt.service);
    const start = new Date(apt.startDateTime);
    setFormDate(start.toISOString().split('T')[0]);
    setFormTime(start.toTimeString().slice(0, 5));
    setFormAddress(apt.address);
    setFormPrice(apt.price);
    setFormNotes(apt.notes);
    setIsModalOpen(true);
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const startIso = new Date(`${formDate}T${formTime}:00`).toISOString();
    const endIso = new Date(new Date(startIso).getTime() + 90 * 60000).toISOString();

    if (editingApt) {
      // Reschedule update
      onUpdateAppointmentStatus(editingApt.id, 'rescheduled');
      const updated: Appointment = {
        ...editingApt,
        customerName: formCustomerName,
        customerPhone: formPhone,
        customerEmail: formEmail,
        service: formService,
        startDateTime: startIso,
        endDateTime: endIso,
        address: formAddress,
        price: Number(formPrice),
        notes: formNotes,
        status: 'rescheduled',
      };
      onAddAppointment(updated);
    } else {
      // New booking
      const newApt: Appointment = {
        id: 'apt-' + Date.now(),
        leadId: 'lead-' + Date.now(),
        customerName: formCustomerName,
        customerPhone: formPhone,
        customerEmail: formEmail,
        service: formService,
        startDateTime: startIso,
        endDateTime: endIso,
        address: formAddress,
        price: Number(formPrice),
        notes: formNotes,
        status: 'confirmed',
      };
      onAddAppointment(newApt);
    }
    setIsModalOpen(false);
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-900 tracking-tight">
            Appointment Calendar & Dispatch
          </h2>
          <p className="text-xs text-slate-500">
            Automated bookings generated by CallBack AI with live Google Calendar synchronization
          </p>
        </div>

        <div className="flex items-center gap-3 w-full sm:w-auto">
          {/* View Toggles */}
          <div className="flex bg-slate-100 p-1 rounded-xl border border-slate-200 text-xs">
            <button
              onClick={() => setViewMode('list')}
              className={`px-3 py-1 rounded-lg font-semibold transition-all ${
                viewMode === 'list' ? 'bg-white shadow text-slate-900' : 'text-slate-500 hover:text-slate-900'
              }`}
            >
              List View
            </button>
            <button
              onClick={() => setViewMode('month')}
              className={`px-3 py-1 rounded-lg font-semibold transition-all ${
                viewMode === 'month' ? 'bg-white shadow text-slate-900' : 'text-slate-500 hover:text-slate-900'
              }`}
            >
              Month Grid
            </button>
          </div>

          <button
            id="btn-book-appointment-manual"
            onClick={handleOpenNewModal}
            className="px-3.5 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-semibold flex items-center gap-1.5 shadow-sm transition-all"
          >
            <Plus className="w-4 h-4" />
            <span>Book Appointment</span>
          </button>
        </div>
      </div>

      {/* Availability Rules Summary Bar */}
      <div className="bg-slate-50 p-4 rounded-xl border border-slate-200/80 flex flex-wrap items-center justify-between gap-4 text-xs">
        <div className="flex items-center gap-6">
          <div>
            <span className="text-slate-400 block text-[10px] uppercase font-bold tracking-wider">
              Buffer Time
            </span>
            <span className="font-bold text-slate-800">
              {businessProfile.availabilityRules.bufferMinutes} mins between visits
            </span>
          </div>
          <div>
            <span className="text-slate-400 block text-[10px] uppercase font-bold tracking-wider">
              Minimum Notice
            </span>
            <span className="font-bold text-slate-800">
              {businessProfile.availabilityRules.minNoticeHours} hours notice
            </span>
          </div>
          <div>
            <span className="text-slate-400 block text-[10px] uppercase font-bold tracking-wider">
              Working Days
            </span>
            <span className="font-bold text-slate-800">
              {businessProfile.availabilityRules.workingDays.length} days/week
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-slate-500 text-[11px]">Primary Calendar:</span>
          <span className="px-2.5 py-1 rounded-lg bg-white border border-slate-200 text-slate-800 font-semibold text-xs flex items-center gap-1.5">
            <CalendarCheck className="w-3.5 h-3.5 text-blue-600" />
            Google Calendar ({isGoogleConnected ? 'Connected' : 'OAuth Ready'})
          </span>
        </div>
      </div>

      {/* Appointments List / Grid */}
      {viewMode === 'list' ? (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50/80 border-b border-slate-200 text-[11px] font-bold uppercase tracking-wider text-slate-500">
                  <th className="py-3 px-4">Date & Time</th>
                  <th className="py-3 px-4">Customer</th>
                  <th className="py-3 px-4">Service</th>
                  <th className="py-3 px-4">Location</th>
                  <th className="py-3 px-4">Status</th>
                  <th className="py-3 px-4">Est. Price</th>
                  <th className="py-3 px-4">Google Calendar</th>
                  <th className="py-3 px-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-xs">
                {appointments.map((apt) => {
                  const startDate = new Date(apt.startDateTime);
                  return (
                    <tr key={apt.id} className="hover:bg-slate-50/80 transition-colors">
                      <td className="py-3.5 px-4 font-bold text-slate-900">
                        <div>{startDate.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}</div>
                        <div className="text-[11px] text-blue-600 font-normal mt-0.5">
                          {startDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </div>
                      </td>

                      <td className="py-3.5 px-4">
                        <div className="font-bold text-slate-900">{apt.customerName}</div>
                        <div className="text-[11px] text-slate-500 font-mono mt-0.5">{apt.customerPhone}</div>
                      </td>

                      <td className="py-3.5 px-4 font-medium text-slate-800">
                        {apt.service}
                      </td>

                      <td className="py-3.5 px-4 text-slate-600 max-w-[200px] truncate">
                        {apt.address}
                      </td>

                      <td className="py-3.5 px-4">
                        <span
                          className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase ${
                            apt.status === 'confirmed'
                              ? 'bg-emerald-100 text-emerald-800'
                              : apt.status === 'rescheduled'
                              ? 'bg-amber-100 text-amber-800'
                              : apt.status === 'completed'
                              ? 'bg-blue-100 text-blue-800'
                              : 'bg-rose-100 text-rose-800'
                          }`}
                        >
                          {apt.status}
                        </span>
                      </td>

                      <td className="py-3.5 px-4 font-bold text-slate-900 font-mono">
                        ${apt.price}
                      </td>

                      <td className="py-3.5 px-4">
                        {isGoogleConnected ? (
                          <button
                            onClick={() => onSyncGoogleCalendar(apt)}
                            className="text-[11px] text-emerald-700 hover:text-emerald-900 flex items-center gap-1 font-semibold"
                          >
                            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                            Synced to Google
                          </button>
                        ) : (
                          <span className="text-[11px] text-slate-400">Not synced</span>
                        )}
                      </td>

                      <td className="py-3.5 px-4 text-right space-x-2">
                        <button
                          onClick={() => handleOpenReschedule(apt)}
                          className="px-2 py-1 text-slate-700 hover:bg-slate-100 rounded text-xs font-semibold"
                        >
                          Reschedule
                        </button>
                        <button
                          onClick={() => onUpdateAppointmentStatus(apt.id, 'cancelled')}
                          className="px-2 py-1 text-rose-600 hover:bg-rose-50 rounded text-xs font-semibold"
                        >
                          Cancel
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        /* Month Grid Visual Layout */
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-slate-900">September 2026</h3>
            <div className="flex items-center gap-1">
              <button className="p-1 rounded hover:bg-slate-100 text-slate-600">
                <ChevronLeft className="w-4 h-4" />
              </button>
              <button className="p-1 rounded hover:bg-slate-100 text-slate-600">
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>

          <div className="grid grid-cols-7 gap-px bg-slate-200 rounded-xl overflow-hidden text-xs">
            {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((d) => (
              <div key={d} className="bg-slate-50 p-2 text-center font-bold text-slate-500 text-[11px]">
                {d}
              </div>
            ))}

            {Array.from({ length: 35 }).map((_, i) => {
              const dayNum = i - 1; // Align to September
              const isCurrentMonth = dayNum > 0 && dayNum <= 30;
              const hasAppointments = appointments.filter((a) => {
                const d = new Date(a.startDateTime).getDate();
                return isCurrentMonth && d === dayNum;
              });

              return (
                <div
                  key={i}
                  className={`min-h-24 p-2 bg-white flex flex-col justify-between ${
                    !isCurrentMonth ? 'bg-slate-50/50 text-slate-300' : 'text-slate-800'
                  }`}
                >
                  <span className="font-bold text-[11px]">{isCurrentMonth ? dayNum : ''}</span>
                  <div className="space-y-1">
                    {hasAppointments.map((apt) => (
                      <div
                        key={apt.id}
                        onClick={() => handleOpenReschedule(apt)}
                        className="p-1 rounded bg-blue-50 border border-blue-200 text-blue-900 text-[10px] truncate cursor-pointer hover:bg-blue-100 transition-colors"
                      >
                        <strong>{new Date(apt.startDateTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</strong> {apt.customerName}
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Booking / Reschedule Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-slate-950/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl w-full max-w-lg shadow-xl border border-slate-200 overflow-hidden">
            <div className="p-4 bg-slate-900 text-white flex items-center justify-between">
              <h3 className="font-bold text-sm">
                {editingApt ? 'Reschedule Appointment' : 'Book New Service Visit'}
              </h3>
              <button onClick={() => setIsModalOpen(false)}>
                <X className="w-5 h-5 text-slate-400 hover:text-white" />
              </button>
            </div>

            <form onSubmit={handleFormSubmit} className="p-5 space-y-3 text-xs">
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-bold text-slate-700 block mb-1">Customer Name *</label>
                  <input
                    type="text"
                    required
                    value={formCustomerName}
                    onChange={(e) => setFormCustomerName(e.target.value)}
                    className="w-full p-2 bg-slate-50 border rounded-lg"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-700 block mb-1">Phone Number *</label>
                  <input
                    type="text"
                    required
                    value={formPhone}
                    onChange={(e) => setFormPhone(e.target.value)}
                    className="w-full p-2 bg-slate-50 border rounded-lg"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-bold text-slate-700 block mb-1">Email</label>
                  <input
                    type="email"
                    value={formEmail}
                    onChange={(e) => setFormEmail(e.target.value)}
                    className="w-full p-2 bg-slate-50 border rounded-lg"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-700 block mb-1">Estimated Price ($)</label>
                  <input
                    type="number"
                    value={formPrice}
                    onChange={(e) => setFormPrice(Number(e.target.value))}
                    className="w-full p-2 bg-slate-50 border rounded-lg"
                  />
                </div>
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">Service</label>
                <select
                  value={formService}
                  onChange={(e) => setFormService(e.target.value)}
                  className="w-full p-2 bg-slate-50 border rounded-lg"
                >
                  {businessProfile.services.map((s) => (
                    <option key={s.id} value={s.name}>
                      {s.name} (${s.priceMin})
                    </option>
                  ))}
                </select>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-bold text-slate-700 block mb-1">Date</label>
                  <input
                    type="date"
                    value={formDate}
                    onChange={(e) => setFormDate(e.target.value)}
                    className="w-full p-2 bg-slate-50 border rounded-lg"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-700 block mb-1">Time</label>
                  <input
                    type="time"
                    value={formTime}
                    onChange={(e) => setFormTime(e.target.value)}
                    className="w-full p-2 bg-slate-50 border rounded-lg"
                  />
                </div>
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">Service Address</label>
                <input
                  type="text"
                  value={formAddress}
                  onChange={(e) => setFormAddress(e.target.value)}
                  className="w-full p-2 bg-slate-50 border rounded-lg"
                />
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">Job Notes</label>
                <textarea
                  rows={2}
                  value={formNotes}
                  onChange={(e) => setFormNotes(e.target.value)}
                  className="w-full p-2 bg-slate-50 border rounded-lg"
                />
              </div>

              <div className="pt-3 flex justify-end gap-2 border-t">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-3.5 py-1.5 rounded-lg border text-slate-600 hover:bg-slate-50"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-1.5 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg shadow-sm"
                >
                  {editingApt ? 'Save Changes' : 'Confirm Booking'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
